# #
# # Copyright (c) New Cloud Technologies, Ltd., 2013-2016
# #
# # You can not use the contents of the file in any way without New Cloud Technologies, Ltd. written permission.
# # To obtain such a permit, you should contact New Cloud Technologies, Ltd. at http://ncloudtech.com/contact.html
# #
#
# -
#     id: 1
#     created: 1459546374
#     name: b_test_product_1
#     version: b_test_1
#     prefix: FP1
# -
#     id: 2
#     created: 1459546374
#     name: b_test_product_2
#     version: b_test_2
#     prefix: FP2
# -
#     id: 3
#     created: 1459546374
#     name: b_test_product_3
#     version: b_test_3
#     prefix:
# -
#     id: 4
#     created: 1459546374
#     name: b_test_product_4
#     version: b_test_4
# -
#     id: 5
#     created: 1459546374
#     name: b_test_product_5
#     version: b_test_5
#     default_license_id: 5
# -
#     id: 6
#     created: 1459546374
#     name: b_test_product_6
#     version: b_test_6
#     prefix: FP6
# -
#     id: 7
#     created: 1459546374
#     name: b_test_product_7
#     version: b_test_7
# -
#     id: 8
#     created: 1459546374
#     name: b_test_product_8
#     version: b_test_8
# -
#     id: 9
#     created: 1459546374
#     name: b_test_product_9
#     version: b_test_9
